export type ResourceCategory =
    | "Healthcare"
    | "Family"
    | "Food"
    | "Seniors"
    | "Legal"
    | "Emergency"
    | "Education"
    | "Community"
    | "Recreation"
    | "Service Stars";

export interface Resource {
    id: string;
    name: string;
    category: ResourceCategory;
    shortDescription: string;
    fullDescription: string;
    address: string;
    mapCoordinates: { lat: number; lng: number };
    phone: string;
    website: string;
    email: string;
    socialLinks?: {
        facebook?: string;
        twitter?: string;
        instagram?: string;
    };
    tags: string[];
    image: string;
    rating: number; // 1-5
}

export const RESOURCES: Resource[] = [
    // Healthcare
    {
        id: "1",
        name: "Harborview Medical Center",
        category: "Healthcare",
        shortDescription: "Comprehensive medical services including emergency care, trauma center, and specialized clinics.",
        fullDescription: "Harborview Medical Center is Port Laken's primary healthcare provider, offering Level I trauma care, burn center services, and comprehensive medical and surgical care. Our dedicated team of specialists is committed to providing high-quality, patient-centered care to all residents.",
        address: "939 Caroline St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1089, lng: -123.4319 },
        phone: "(206) 744-3000",
        website: "https://www.harborview.org",
        email: "info@harborview.org",
        socialLinks: { facebook: "fb.com/harborview", twitter: "@harborview" },
        tags: ["hospital", "emergency", "trauma", "medical"],
        image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
        rating: 4.8
    },
    {
        id: "2",
        name: "Port Laken Community Clinic",
        category: "Healthcare",
        shortDescription: "Affordable primary care and walk-in services for families and individuals.",
        fullDescription: "The Community Clinic provides essential primary care services, including routine check-ups, vaccinations, and chronic disease management. We offer a sliding scale fee structure to ensure accessibility for all community members.",
        address: "240 W Front St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1188, lng: -123.4397 },
        phone: "(206) 555-0102",
        website: "https://plcommunityclinic.org",
        email: "contact@plclinic.org",
        tags: ["clinic", "primary care", "affordable"],
        image: "https://images.unsplash.com/photo-1519494080410-f9aa76cb4283?w=800&q=80",
        rating: 4.5
    },
    {
        id: "3",
        name: "Laken Dental Health",
        category: "Healthcare",
        shortDescription: "Comprehensive dental care for children and adults.",
        fullDescription: "From cleanings to oral surgery, Laken Dental Health provides full-service dental care. We accept most insurance plans and offer emergency dental services.",
        address: "228 W 1st St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1185, lng: -123.4395 },
        phone: "(206) 555-0123",
        website: "https://lakendental.com",
        email: "appt@lakendental.com",
        tags: ["dentist", "dental", "oral health"],
        image: "https://images.unsplash.com/photo-1445527815219-ecbfec67492e?w=800&q=80",
        rating: 4.7
    },
    {
        id: "4",
        name: "Vision Plus Eye Care",
        category: "Healthcare",
        shortDescription: "Optometry services and eyewear.",
        fullDescription: "Comprehensive eye exams, contact lens fittings, and a wide selection of frames. Our optometrists are dedicated to preserving and enhancing your vision.",
        address: "819 E Georgiana St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1154, lng: -123.4163 },
        phone: "(206) 555-0199",
        website: "https://visionpluspl.com",
        email: "see@visionpluspl.com",
        tags: ["vision", "optometry", "glasses"],
        image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&q=80",
        rating: 4.6
    },
    {
        id: "5",
        name: "Port Laken Mental Health Services",
        category: "Healthcare",
        shortDescription: "Counseling and therapy for all ages.",
        fullDescription: "Professional mental health support including individual therapy, couples counseling, and group sessions. We specialize in anxiety, depression, and trauma recovery.",
        address: "118 E 8th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.112, lng: -123.427 },
        phone: "(206) 555-0800",
        website: "https://plmentalhealth.org",
        email: "help@plmentalhealth.org",
        tags: ["mental health", "therapy", "counseling"],
        image: "https://images.unsplash.com/photo-1516302752625-fcc3c50ae61f?w=800&q=80",
        rating: 4.9
    },

    // Family
    {
        id: "6",
        name: "Eastlaken Community Center",
        category: "Family",
        shortDescription: "Family programs, youth activities, and community events.",
        fullDescription: "A vibrant hub for the Eastlaken neighborhood, offering after-school programs, summer camps, fitness classes, and community meeting spaces. Join us for weekly movie nights and seasonal festivals.",
        address: "308 E 4th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1167, lng: -123.4282 },
        phone: "(206) 555-1234",
        website: "https://eastlakencc.org",
        email: "info@eastlakencc.org",
        socialLinks: { instagram: "@eastlaken_cc" },
        tags: ["community center", "youth", "family", "activities"],
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
        rating: 4.8
    },
    {
        id: "7",
        name: "Little Stars Daycare",
        category: "Family",
        shortDescription: "Licensed childcare and early learning.",
        fullDescription: "Providing a safe, nurturing environment for children aged 6 months to 5 years. Our curriculum focuses on social-emotional development and early literacy.",
        address: "325 E 6th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1141, lng: -123.4279 },
        phone: "(206) 555-2200",
        website: "https://littlestarspl.com",
        email: "enroll@littlestarspl.com",
        tags: ["childcare", "daycare", "preschool"],
        image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&q=80",
        rating: 4.7
    },
    {
        id: "8",
        name: "Port Laken Parenting Support",
        category: "Family",
        shortDescription: "Workshops and resources for new parents.",
        fullDescription: "Free workshops on breastfeeding, sleep training, and positive discipline. Connect with other parents in our weekly support groups.",
        address: "1210 E Front St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.119, lng: -123.4168 },
        phone: "(206) 555-2345",
        website: "https://plparenting.org",
        email: "support@plparenting.org",
        tags: ["parenting", "support", "workshops"],
        image: "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?w=800&q=80",
        rating: 4.6
    },
    {
        id: "9",
        name: "Boys & Girls Club of Port Laken",
        category: "Family",
        shortDescription: "Youth mentorship and recreation programs.",
        fullDescription: "Empowering young people to reach their full potential. We offer sports leagues, homework help, and arts programs for kids and teens.",
        address: "2620 S Francis St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.0955, lng: -123.4412 },
        phone: "(206) 555-8888",
        website: "https://bgcpl.org",
        email: "contact@bgcpl.org",
        tags: ["youth", "mentorship", "recreation"],
        image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80",
        rating: 4.9
    },
    {
        id: "10",
        name: "Family First Resource Center",
        category: "Family",
        shortDescription: "Connecting families with essential services.",
        fullDescription: "Your one-stop shop for accessing housing assistance, food benefits, and employment resources. Our case managers are here to advocate for your family.",
        address: "2203 W 18th St, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.0978, lng: -123.4607 },
        phone: "(206) 555-9000",
        website: "https://familyfirstpl.org",
        email: "help@familyfirstpl.org",
        tags: ["resource center", "social services", "advocacy"],
        image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800&q=80",
        rating: 4.5
    },

    // Food
    {
        id: "11",
        name: "Port Laken Food Bank",
        category: "Food",
        shortDescription: "Food assistance for families in need.",
        fullDescription: "Providing nutritious groceries to individuals and families experiencing food insecurity. No ID required. Open Mondays, Wednesdays, and Fridays.",
        address: "632 N Oakridge Dr, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1338, lng: -123.439 },
        phone: "(206) 555-4321",
        website: "https://plfoodbank.org",
        email: "volunteer@plfoodbank.org",
        socialLinks: { facebook: "fb.com/plfoodbank" },
        tags: ["food bank", "groceries", "assistance"],
        image: "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800&q=80",
        rating: 4.8
    },
    {
        id: "12",
        name: "Meals on Wheels Port Laken",
        category: "Food",
        shortDescription: "Home-delivered meals for seniors and homebound residents.",
        fullDescription: "Nutritious meals delivered directly to your door. We also conduct safety checks and provide social interaction for our clients.",
        address: "228 E 1st St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1185, lng: -123.4289 },
        phone: "(206) 555-5555",
        website: "https://mowpl.org",
        email: "signup@mowpl.org",
        tags: ["seniors", "delivery", "nutrition"],
        image: "https://images.unsplash.com/photo-1607478900766-efe13248b125?w=800&q=80",
        rating: 4.9
    },
    {
        id: "13",
        name: "Urban Harvest Community Garden",
        category: "Food",
        shortDescription: "Grow your own food and learn about urban farming.",
        fullDescription: "A shared green space where residents can rent plots to grow vegetables and flowers. We offer gardening workshops and donate surplus produce to local food banks.",
        address: "2601 S Francis St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.0957, lng: -123.441 },
        phone: "(206) 555-6789",
        website: "https://urbanharvestpl.org",
        email: "grow@urbanharvestpl.org",
        tags: ["garden", "fresh food", "community"],
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
        rating: 4.7
    },
    {
        id: "14",
        name: "The Soup Kitchen",
        category: "Food",
        shortDescription: "Hot daily meals for anyone hungry.",
        fullDescription: "Serving hot, nutritious lunches and dinners seven days a week. Everyone is welcome at our table.",
        address: "216 S Peabody St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1159, lng: -123.4322 },
        phone: "(206) 555-9876",
        website: "https://thesoupkitchenpl.org",
        email: "info@thesoupkitchenpl.org",
        tags: ["meals", "homeless", "hot food"],
        image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
        rating: 4.6
    },

    // Seniors
    {
        id: "15",
        name: "Golden Years Senior Center",
        category: "Seniors",
        shortDescription: "Activities, classes, and support services for seniors 60+.",
        fullDescription: "Join us for fitness classes, art workshops, technology training, and social events. We also offer caregiver support and resource referrals.",
        address: "328 E 7th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1128, lng: -123.4279 },
        phone: "(206) 555-6060",
        website: "https://gyscpl.org",
        email: "programs@gyscpl.org",
        tags: ["seniors", "activities", "social"],
        image: "https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=800&q=80",
        rating: 4.7
    },
    {
        id: "16",
        name: "Senior Transport Services",
        category: "Seniors",
        shortDescription: "Free transportation for medical appointments and grocery shopping.",
        fullDescription: "Volunteer drivers provide door-to-door transportation for eligible seniors. Advance reservation required.",
        address: "830 W Lauridsen Blvd, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1097, lng: -123.4571 },
        phone: "(206) 555-7070",
        website: "https://seniortransportpl.org",
        email: "ride@seniortransportpl.org",
        tags: ["transportation", "seniors", "mobility"],
        image: "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=800&q=80",
        rating: 4.8
    },
    {
        id: "17",
        name: "StoryPoint Senior Living",
        category: "Seniors",
        shortDescription: "Independent and assisted living community.",
        fullDescription: "Comfortable apartments with dining services, housekeeping, and nursing care available. Enjoy stunning views of the lake and a vibrant social calendar.",
        address: "1430 Park View Ln, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1052, lng: -123.4298 },
        phone: "(206) 555-8080",
        website: "https://storypointpl.com",
        email: "welcome@storypointpl.com",
        tags: ["housing", "assisted living", "retirement"],
        image: "https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=800&q=80",
        rating: 4.5
    },

    // Legal
    {
        id: "18",
        name: "Community Legal Services",
        category: "Legal",
        shortDescription: "Free legal assistance for low-income residents.",
        fullDescription: "Providing legal aid for housing disputes, family law, consumer protection, and immigration issues. We ensure equal access to justice.",
        address: "528 W 8th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.111, lng: -123.4462 },
        phone: "(206) 555-9999",
        website: "https://clspl.org",
        email: "intake@clspl.org",
        tags: ["legal aid", "pro bono", "lawyer"],
        image: "https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800&q=80",
        rating: 4.8
    },
    {
        id: "19",
        name: "Tenant Rights Union",
        category: "Legal",
        shortDescription: "Advocacy and education for renters.",
        fullDescription: "Know your rights as a tenant. We offer counseling on eviction prevention, lease agreements, and repair issues.",
        address: "319 S Peabody St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1151, lng: -123.4323 },
        phone: "(206) 555-0011",
        website: "https://tenantrightspl.org",
        email: "help@tenantrightspl.org",
        tags: ["housing", "tenants", "legal"],
        image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
        rating: 4.6
    },

    // Emergency
    {
        id: "20",
        name: "Port Laken Police Department - Central Precinct",
        category: "Emergency",
        shortDescription: "Law enforcement and public safety.",
        fullDescription: "Serving the downtown and central neighborhoods. For emergencies, always dial 911. For non-emergencies, call (206) 625-5011.",
        address: "321 E 5th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1158, lng: -123.4297 },
        phone: "911",
        website: "https://police.portlaken.gov",
        email: "police@portlaken.gov",
        tags: ["police", "safety", "emergency"],
        image: "https://images.unsplash.com/photo-1453873531674-2151bcd01707?w=800&q=80",
        rating: 4.2
    },
    {
        id: "21",
        name: "Fire Station 10",
        category: "Emergency",
        shortDescription: "Fire suppression and emergency medical services.",
        fullDescription: "Ready to respond to fires, medical emergencies, and rescue operations. Visit us for free blood pressure checks.",
        address: "102 E 5th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1158, lng: -123.435 },
        phone: "911",
        website: "https://fire.portlaken.gov",
        email: "fireinfo@portlaken.gov",
        tags: ["fire", "ems", "emergency"],
        image: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800&q=80",
        rating: 4.8
    },
    {
        id: "22",
        name: "Domestic Violence Hotline",
        category: "Emergency",
        shortDescription: "24/7 confidential support for survivors.",
        fullDescription: "Immediate crisis intervention, safety planning, and shelter referrals. You are not alone.",
        address: "272 W Bell St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1072, lng: -123.4421 },
        phone: "1-800-555-SAFE",
        website: "https://dvhopepl.org",
        email: "safe@dvhopepl.org",
        tags: ["crisis", "support", "hotline"],
        image: "https://images.unsplash.com/photo-1520315342629-6ea920342047?w=800&q=80",
        rating: 4.9
    },

    // Education
    {
        id: "23",
        name: "Port Laken Public Library - Central",
        category: "Education",
        shortDescription: "Books, technology, and learning for everyone.",
        fullDescription: "An architectural marvel and a center for knowledge. Access computers, free wifi, job search assistance, and millions of books.",
        address: "2210 S Peabody St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.0988, lng: -123.4322 },
        phone: "(206) 386-4636",
        website: "https://spl.org",
        email: "librarian@spl.org",
        tags: ["library", "books", "internet"],
        image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80",
        rating: 4.9
    },
    {
        id: "24",
        name: "Lakefront High School",
        category: "Education",
        shortDescription: "Public high school serving grades 9-12.",
        fullDescription: "Home of the Lakers. Dedicated to academic excellence and preparing students for college and careers.",
        address: "304 E Park Ave, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1082, lng: -123.4243 },
        phone: "(206) 555-3000",
        website: "https://lakefronths.portlaken.k12.wa.us",
        email: "office@lakefronths.k12.wa.us",
        tags: ["school", "high school", "education"],
        image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
        rating: 4.4
    },
    {
        id: "25",
        name: "Port Laken Community College",
        category: "Education",
        shortDescription: "Affordable higher education and workforce training.",
        fullDescription: "Offering associate degrees, vocational certificates, and transfer programs. Start your future here.",
        address: "1502 E Lauridsen Blvd, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1073, lng: -123.4162 },
        phone: "(206) 934-3800",
        website: "https://seattlecentral.edu",
        email: "info@seattlecentral.edu",
        tags: ["college", "education", "training"],
        image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
        rating: 4.6
    },
    {
        id: "26",
        name: "Olympic University",
        category: "Education",
        shortDescription: "A top-20 global research university on the Pacific Rim.",
        fullDescription: "Olympic University is a world-leading research institution with global strength in chemistry, molecular biology, law, and international law. Known for Nobel-level scientific research, elite legal scholarship, and strong ties to global policy institutions across the Pacific and Europe.",
        address: "1700 E Lauridsen Blvd, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1071, lng: -123.414 },
        phone: "(360) 555-2201",
        website: "https://olympicu.edu",
        email: "admissions@olympicu.edu",
        tags: ["university", "research", "top-20", "chemistry", "biology", "law", "international law"],
        image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
        rating: 4.8
    },
    {
        id: "41",
        name: "Early Learning Center",
        category: "Education",
        shortDescription: "Head Start and ECEAP programs.",
        fullDescription: "Free preschool for income-eligible families. We support the whole child and the whole family.",
        address: "3055 Black Diamond Rd, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.0948, lng: -123.4189 },
        phone: "(206) 555-4000",
        website: "https://elcpl.org",
        email: "enroll@elcpl.org",
        tags: ["preschool", "head start", "education"],
        image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&q=80",
        rating: 4.8
    },
    {
        id: "27",
        name: "Port Laken Montessori School",
        category: "Education",
        shortDescription: "Child-centered Montessori early learning.",
        fullDescription: "Serving children ages 2.5–6 through accredited Montessori programs that foster independence, curiosity, and confidence in a nurturing classroom environment.",
        address: "905 W 9th St, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.1106, lng: -123.4543 },
        phone: "(206) 555-4123",
        website: "https://plmontessori.org",
        email: "admissions@plmontessori.org",
        tags: ["montessori", "preschool", "early learning"],
        image: "https://images.unsplash.com/photo-1567057419565-4349c49d8a04?w=800&q=80",
        rating: 4.7
    },
    {
        id: "29",
        name: "Port Laken KinderCare",
        category: "Education",
        shortDescription: "Early education and child care for infants through pre-K.",
        fullDescription: "Providing licensed child care and early learning programs for infants, toddlers, preschool, and pre-kindergarten. Our curriculum supports social, emotional, and academic development in a safe, structured environment.",
        address: "2001 W 18th St, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.097, lng: -123.4601 },
        phone: "(206) 555-4520",
        website: "https://www.kindercare.com",
        email: "portlaken@kindercare.com",
        tags: ["childcare", "early learning", "preschool", "pre-k"],
        image: "https://images.unsplash.com/photo-1555252333-9f8e92e65df9?w=800&q=80",
        rating: 4.4
    },

    // Community
    {
        id: "42",
        name: "Port Laken City Hall",
        category: "Community",
        shortDescription: "Municipal government services.",
        fullDescription: "Pay utility bills, apply for permits, and attend city council meetings. Your local government at work.",
        address: "223 E 4th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.117, lng: -123.4288 },
        phone: "(206) 684-2489",
        website: "https://portlaken.gov",
        email: "mayor@portlaken.gov",
        tags: ["government", "city", "services"],
        image: "https://images.unsplash.com/photo-1523292562811-8fa7962a78c8?w=800&q=80",
        rating: 4.3
    },
    {
        id: "28",
        name: "Downtown Neighborhood Association",
        category: "Community",
        shortDescription: "Advocating for downtown residents.",
        fullDescription: "Promoting a safe, clean, and vibrant downtown neighborhood. Monthly meetings open to all residents.",
        address: "124 W Railroad Ave, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1192, lng: -123.4398 },
        phone: "(206) 555-9988",
        website: "https://dnapl.org",
        email: "board@dnapl.org",
        tags: ["neighborhood", "community", "advocacy"],
        image: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80",
        rating: 4.5
    },
    {
        id: "43",
        name: "Port Laken Humane Society",
        category: "Community",
        shortDescription: "Animal shelter and adoption center.",
        fullDescription: "Find your new best friend. We offer pet adoptions, low-cost spay/neuter services, and dog training classes.",
        address: "1743 Old Olympic Hwy, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.1025, lng: -123.4699 },
        phone: "(425) 641-0080",
        website: "https://plhumane.org",
        email: "adopt@plhumane.org",
        tags: ["animals", "pets", "adoption"],
        image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&q=80",
        rating: 4.8
    },

    // Recreation
    {
        id: "30",
        name: "Green Lake Park",
        category: "Recreation",
        shortDescription: "Urban park with a lake, trails, and sports fields.",
        fullDescription: "One of Port Laken's most beloved parks. Walk or run the 2.8-mile path around the lake, rent a paddleboat, or play tennis.",
        address: "315 N Lincoln St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.123, lng: -123.4379 },
        phone: "(206) 684-4075",
        website: "https://seattle.gov/parks",
        email: "parks@portlaken.gov",
        tags: ["park", "nature", "sports"],
        image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
        rating: 4.9
    },
    {
        id: "31",
        name: "Port Laken Aquarium",
        category: "Recreation",
        shortDescription: "Discover the marine life of the Pacific Northwest.",
        fullDescription: "Explore exhibits featuring sea otters, octopuses, and colorful fish. Great family fun on the waterfront.",
        address: "101 E Railroad Ave, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1191, lng: -123.4362 },
        phone: "(206) 386-4300",
        website: "https://seattleaquarium.org",
        email: "info@seattleaquarium.org",
        tags: ["aquarium", "family", "fun"],
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
        rating: 4.6
    },
    {
        id: "32",
        name: "Discovery Park",
        category: "Recreation",
        shortDescription: "Largest city park with beaches and forest trails.",
        fullDescription: "A natural sanctuary in the city. Hike through forests, walk along the sandy beach, and visit the historic West Point Lighthouse.",
        address: "3000 W Lauridsen Blvd, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.1152, lng: -123.4756 },
        phone: "(206) 386-4236",
        website: "https://seattle.gov/parks",
        email: "parks@portlaken.gov",
        tags: ["hiking", "beach", "nature"],
        image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
        rating: 4.9
    },
    {
        id: "33",
        name: "Yoga by the Lake",
        category: "Recreation",
        shortDescription: "Community yoga studio.",
        fullDescription: "Offering Vinyasa, Hatha, and Yin yoga classes for all levels. First class is free.",
        address: "302 S Francis St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1048, lng: -123.4405 },
        phone: "(206) 555-1080",
        website: "https://yogabylakepl.com",
        email: "namaste@yogabylakepl.com",
        tags: ["yoga", "fitness", "wellness"],
        image: "https://images.unsplash.com/photo-1588286840104-8957b019727f?w=800&q=80",
        rating: 4.8
    },
    {
        id: "34",
        name: "CrossFit Port Laken",
        category: "Recreation",
        shortDescription: "Functional fitness gym.",
        fullDescription: "High-intensity workouts led by certified coaches. Build strength and community.",
        address: "224 E First St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1191, lng: -123.4283 },
        phone: "(206) 555-9900",
        website: "https://www.crossfit.com/",
        email: "portlaken@crossfit.com",
        tags: ["gym", "fitness", "workout"],
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
        rating: 4.7
    },

    // More Education
    {
        id: "35",
        name: "iCode Port Laken",
        category: "Education",
        shortDescription: "STEM education and coding for kids and teens.",
        fullDescription: "iCode Port Laken offers after-school programs, camps, and competitive coding experiences for students ages 6–18. Courses include coding, robotics, game development, and AI fundamentals in a collaborative, project-based environment.",
        address: "433 E 8th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1119, lng: -123.4218 },
        phone: "(206) 555-4263",
        website: "https://www.icodeschool.com",
        email: "portlaken@icodeschool.com",
        tags: ["coding", "stem", "education"],
        image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80",
        rating: 4.6
    },

    // More Community
    {
        id: "36",
        name: "Port Laken Art Museum",
        category: "Community",
        shortDescription: "Contemporary and classic art exhibits.",
        fullDescription: "Experience world-class art right here in Port Laken. Free admission on first Thursdays.",
        address: "1203 E Lauridsen Blvd, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1072, lng: -123.4171 },
        phone: "(206) 654-3100",
        website: "https://seattleartmuseum.org",
        email: "visit@portlakenart.org",
        tags: ["art", "culture", "museum"],
        image: "https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=800&q=80",
        rating: 4.7
    },
    {
        id: "37",
        name: "Volunteer Port Laken",
        category: "Community",
        shortDescription: "Connecting volunteers with non-profits.",
        fullDescription: "Find meaningful volunteer opportunities that match your skills and interests. Give back to your community.",
        address: "1601 E Front St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.119, lng: -123.4127 },
        phone: "(206) 555-VOLS",
        website: "https://volunteerpl.org",
        email: "helpout@volunteerpl.org",
        tags: ["volunteer", "service", "non-profit"],
        image: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800&q=80",
        rating: 4.8
    },

    // More Food
    {
        id: "38",
        name: "Fresh Market Co-op",
        category: "Food",
        shortDescription: "Community-owned grocery store.",
        fullDescription: "Organic, local, and sustainable food. Open to everyone, members get discounts.",
        address: "125 E Front St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1189, lng: -123.4366 },
        phone: "(206) 555-FARM",
        website: "https://centralcoop.coop",
        email: "info@centralcoop.coop",
        tags: ["grocery", "organic", "local"],
        image: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&q=80",
        rating: 4.5
    },

    // More Seniors
    {
        id: "39",
        name: "Silver Sneakers Club",
        category: "Seniors",
        shortDescription: "Fitness program for older adults.",
        fullDescription: "Stay active and healthy with our specialized fitness classes designed for seniors.",
        address: "114 S Lincoln St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1172, lng: -123.4369 },
        phone: "1-888-423-4632",
        website: "https://silversneakers.com",
        email: "support@silversneakers.com",
        tags: ["fitness", "seniors", "health"],
        image: "https://images.unsplash.com/photo-1554284126-aa88f22d8b74?w=800&q=80",
        rating: 4.6
    },

    // More Housing
    {
        id: "40",
        name: "Port Laken Housing Authority",
        category: "Family",
        shortDescription: "Affordable housing programs.",
        fullDescription: "Providing stable, quality housing for low-income families, seniors, and people with disabilities.",
        address: "2603 S Francis St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.0974, lng: -123.4404 },
        phone: "(206) 615-3300",
        website: "https://seattlehousing.org",
        email: "info@seattlehousing.org",
        tags: ["housing", "affordable", "government"],
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
        rating: 4.4
    },

    // Parks - From Environmental Page
    {
        id: "44",
        name: "Elm Street Park",
        category: "Recreation",
        shortDescription: "Port Laken's newest green space with walking trails and community pavilion.",
        fullDescription: "Elm Street Park is Port Laken's newest green space, opened January 2026. Built on a former industrial lot, it features walking trails, a native plant garden, and a community pavilion. Benches throughout provide restful spots to enjoy the landscape.",
        address: "200 Elm St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1145, lng: -123.4285 },
        phone: "(206) 684-4075",
        website: "https://seattle.gov/parks",
        email: "parks@portlaken.gov",
        tags: ["park", "green space", "trails", "pavilion", "community"],
        image: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&q=80",
        rating: 4.9
    },
    {
        id: "45",
        name: "Lakeview Waterfront Park",
        category: "Recreation",
        shortDescription: "14-acre waterfront park with boat launch and restored habitat.",
        fullDescription: "A 14-acre waterfront park along the Port Laken shoreline offering picnic areas, a boat launch, and restored wetland habitat. The Wetland Trail provides scenic views and opportunities for bird watching. Fishing is available from the designated pier.",
        address: "1850 Harbor Ave, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1265, lng: -123.4256 },
        phone: "(206) 684-4075",
        website: "https://seattle.gov/parks",
        email: "parks@portlaken.gov",
        tags: ["park", "waterfront", "boating", "fishing", "picnic"],
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
        rating: 4.8
    },
    {
        id: "46",
        name: "Riverside Community Garden",
        category: "Food",
        shortDescription: "Community garden with 80+ plots and composting facilities.",
        fullDescription: "One of 12 community garden sites in Port Laken, Riverside hosts over 80 active garden plots alongside a composting station. Gardeners enjoy shared tool shed access and attend seasonal workshops on urban farming and sustainable gardening practices.",
        address: "950 River Rd, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1095, lng: -123.4350 },
        phone: "(206) 555-6789",
        website: "https://urbanharvestpl.org",
        email: "grow@urbanharvestpl.org",
        tags: ["community garden", "urban farming", "composting", "food"],
        image: "https://images.unsplash.com/photo-1464226184081-280282a76e63?w=800&q=80",
        rating: 4.7
    },

    // Restaurants - From News Articles
    {
        id: "47",
        name: "Portside Grille",
        category: "Food",
        shortDescription: "Downtown restaurant committed to supporting local food networks.",
        fullDescription: "Portside Grille is a downtown dining destination that partners with the Port Laken Community Food Network to donate surplus food. The restaurant specializes in fresh, locally-sourced ingredients and is deeply invested in community food security initiatives.",
        address: "425 S Peabody St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1140, lng: -123.4325 },
        phone: "(206) 555-3050",
        website: "https://portside-grille.com",
        email: "info@portside-grille.com",
        tags: ["restaurant", "dining", "local", "food"],
        image: "https://images.unsplash.com/photo-1517457373614-b7152f800fd1?w=800&q=80",
        rating: 4.7
    },
    {
        id: "48",
        name: "Canela",
        category: "Food",
        shortDescription: "Community-focused restaurant supporting local food initiatives.",
        fullDescription: "Owned by David Okafor, Canela is a restaurant dedicated to community engagement and food sustainability. As an early partner with the Port Laken Community Food Network, Canela participates in the weekly surplus food program that rescues nutritious meals for families in need.",
        address: "520 S Peabody St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1135, lng: -123.4330 },
        phone: "(206) 555-3055",
        website: "https://canela-restaurant.com",
        email: "reservations@canela-restaurant.com",
        tags: ["restaurant", "community", "sustainable", "dining"],
        image: "https://images.unsplash.com/photo-1504674900968-e4355a63dee2?w=800&q=80",
        rating: 4.8
    },
    {
        id: "49",
        name: "The Mariner",
        category: "Food",
        shortDescription: "Waterfront restaurant partnering with community food programs.",
        fullDescription: "The Mariner is a waterfront restaurant committed to reducing food waste and supporting community nutrition programs. As a key partner with the Port Laken Community Food Network, The Mariner participates in initiatives to donate surplus food to families in need.",
        address: "615 N Harbor Ave, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1210, lng: -123.4245 },
        phone: "(206) 555-3060",
        website: "https://the-mariner-restaurant.com",
        email: "info@the-mariner.com",
        tags: ["restaurant", "waterfront", "food", "community"],
        image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80",
        rating: 4.6
    },

    // Community Businesses
    {
        id: "50",
        name: "Harbor Brew Coffee",
        category: "Community",
        shortDescription: "Local coffee shop that donates profits to homeless shelters.",
        fullDescription: "Harbor Brew Coffee is a beloved Main Street café committed to making a difference in the community. The coffee shop donates 10% of profits to local homeless shelters and is a gathering place that reflects Port Laken's values of connection and compassion.",
        address: "310 E Main St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1188, lng: -123.4310 },
        phone: "(206) 555-2900",
        website: "https://harborbrewcoffee.com",
        email: "hello@harborbrewcoffee.com",
        socialLinks: { instagram: "@harborbrewcoffee" },
        tags: ["coffee", "café", "community", "social mission"],
        image: "https://images.unsplash.com/photo-1559056199-641a0ac8b3f0?w=800&q=80",
        rating: 4.8
    },
    {
        id: "51",
        name: "Pages & Prose",
        category: "Community",
        shortDescription: "Independent bookstore hosting community reading clubs.",
        fullDescription: "Pages & Prose is a cozy independent bookstore that serves as a cultural hub for Port Laken. The shop hosts weekly reading clubs, author events, and community gatherings, creating a welcoming space for book lovers and lifelong learners.",
        address: "225 E Front St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1183, lng: -123.4360 },
        phone: "(206) 555-2700",
        website: "https://pages-and-prose.com",
        email: "info@pagesandprose.com",
        tags: ["bookstore", "reading", "community", "events"],
        image: "https://images.unsplash.com/photo-1507842931343-583f7270bffd?w=800&q=80",
        rating: 4.7
    },
    {
        id: "52",
        name: "Green Thumb Nursery",
        category: "Community",
        shortDescription: "Family-owned nursery specializing in native plants and sustainable landscaping.",
        fullDescription: "Green Thumb Nursery is a three-generation family business specializing in native plants and sustainable landscaping. Located at 789 Cedar Lane, the nursery offers free consultations, native landscaping workshops, and expert advice on creating thriving, environmentally-conscious gardens.",
        address: "789 Cedar Lane, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1102, lng: -123.4241 },
        phone: "(206) 555-3200",
        website: "https://greenthumbportlaken.com",
        email: "info@greenthumbportlaken.com",
        tags: ["nursery", "native plants", "gardening", "sustainability"],
        image: "https://images.unsplash.com/photo-1585320736145-e5c6b3e08d26?w=800&q=80",
        rating: 4.8
    },

    // Community Organizations & Centers
    {
        id: "53",
        name: "Harbor Community Center",
        category: "Community",
        shortDescription: "Community gathering space hosting workshops and community events.",
        fullDescription: "Harbor Community Center is a welcoming community gathering space that hosts a variety of programs including cooking classes, food network information sessions, and community events. The center provides meeting rooms and facilities for local organizations and residents.",
        address: "1425 Harbor Ave, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1220, lng: -123.4240 },
        phone: "(206) 555-4500",
        website: "https://harborcommunitycenter.org",
        email: "info@harborcommunitycenter.org",
        tags: ["community center", "events", "programs", "gathering"],
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
        rating: 4.6
    },
    {
        id: "54",
        name: "Future Forward Port Laken",
        category: "Family",
        shortDescription: "Youth mentorship program providing transformational relationships.",
        fullDescription: "Future Forward Port Laken is a mentorship organization dedicated to supporting young people through meaningful, long-term relationships. Founded by Michael Chen in 2013, the program pairs mentors with mentees for at least two years, with a commitment to reliability, consistency, and positive outcomes. The program has supported over 200 young people with 94% high school graduation rate.",
        address: "1720 Clement St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1164, lng: -123.4295 },
        phone: "(206) 555-7800",
        website: "https://futureforwardportlaken.org",
        email: "info@futureforwardportlaken.org",
        tags: ["mentorship", "youth", "education", "community"],
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
        rating: 4.9
    },
    {
        id: "55",
        name: "Westside Elementary School",
        category: "Education",
        shortDescription: "Public elementary school serving Port Laken's west side.",
        fullDescription: "Westside Elementary is a public elementary school committed to providing quality education and fostering community connections. The school engages with local organizations and community initiatives, such as partnering with the Port Laken Community Food Network and creating collaborative art projects.",
        address: "1850 W 12th St, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.1050, lng: -123.4480 },
        phone: "(206) 555-3500",
        website: "https://westsideelementary.portlaken.k12.wa.us",
        email: "office@westsideelementary.k12.wa.us",
        tags: ["school", "elementary", "education", "public"],
        image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
        rating: 4.5
    },

    // Recreation - Waterfront / Watersports
    {
        id: "56",
        name: "Laken Watersports Co.",
        category: "Recreation",
        shortDescription: "Kayak, paddleboard, and jet ski rentals on the waterfront.",
        fullDescription: "Laken Watersports Co. is Port Laken's premier waterfront adventure hub. Rent kayaks, stand-up paddleboards, canoes, and jet skis by the hour or the day. We also offer guided tours of the harbor, beginner surf lessons, and seasonal whale-watching excursions. All equipment and safety gear included.",
        address: "200 N Harbor Ave, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1225, lng: -123.4260 },
        phone: "(206) 555-7700",
        website: "https://lakenwatersports.com",
        email: "paddle@lakenwatersports.com",
        socialLinks: { instagram: "@lakenwatersports" },
        tags: ["kayak", "paddleboard", "jet ski", "watersports", "beach", "waterfront"],
        image: "https://images.unsplash.com/photo-1530053969600-caed2596d242?w=800&q=80",
        rating: 4.8
    },

    // Legal
    {
        id: "57",
        name: "Port Laken Immigration Law Clinic",
        category: "Legal",
        shortDescription: "Free immigration legal services for residents and families.",
        fullDescription: "The Immigration Law Clinic provides free and low-cost legal assistance for visa applications, DACA renewals, asylum cases, naturalization, and family-based petitions. Staffed by licensed immigration attorneys and supervised law students, we serve Port Laken's diverse immigrant community with compassion and expertise.",
        address: "412 E 3rd St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1175, lng: -123.4270 },
        phone: "(206) 555-0055",
        website: "https://plimmigrationclinic.org",
        email: "intake@plimmigrationclinic.org",
        tags: ["immigration", "legal aid", "visa", "DACA", "asylum"],
        image: "https://images.unsplash.com/photo-1521791055366-0d553872952f?w=800&q=80",
        rating: 4.7
    },

    // Family
    {
        id: "58",
        name: "Port Laken Foster & Adoption Services",
        category: "Family",
        shortDescription: "Support and resources for foster and adoptive families.",
        fullDescription: "Connecting children in need with loving families. We provide training, licensing support, and ongoing case management for foster and adoptive parents. Our team offers 24/7 crisis support and connects families with counseling, respite care, and community networks.",
        address: "1105 E 5th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1155, lng: -123.4195 },
        phone: "(206) 555-3388",
        website: "https://plfosteradopt.org",
        email: "families@plfosteradopt.org",
        tags: ["foster care", "adoption", "family", "children"],
        image: "https://images.unsplash.com/photo-1491013516836-7db643ee125a?w=800&q=80",
        rating: 4.8
    },
    {
        id: "59",
        name: "Laken Family Counseling Center",
        category: "Family",
        shortDescription: "Affordable family and couples therapy.",
        fullDescription: "The Laken Family Counseling Center offers sliding-scale therapy for families, couples, and individuals navigating life transitions, conflict, grief, and trauma. Our licensed therapists specialize in family systems, child behavioral issues, and co-parenting support.",
        address: "730 W 8th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1108, lng: -123.4490 },
        phone: "(206) 555-4411",
        website: "https://lakenfamilycounseling.org",
        email: "appointments@lakenfamilycounseling.org",
        tags: ["counseling", "therapy", "family", "couples"],
        image: "https://images.unsplash.com/photo-1573497491765-dccce02b29df?w=800&q=80",
        rating: 4.6
    },

    // Service Stars
    {
        id: "60",
        name: "Port Laken Community Food Network",
        category: "Service Stars",
        shortDescription: "Citywide network rescuing surplus food and feeding families in need.",
        fullDescription: "The Port Laken Community Food Network coordinates with local restaurants, grocery stores, and farms to rescue surplus food and redistribute it to families experiencing food insecurity. The network operates weekly distribution events across the city and partners with schools, community centers, and faith organizations to reach those most in need.",
        address: "500 E 4th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1168, lng: -123.4260 },
        phone: "(206) 555-6100",
        website: "https://plfoodnetwork.org",
        email: "connect@plfoodnetwork.org",
        socialLinks: { facebook: "fb.com/plfoodnetwork", instagram: "@plfoodnetwork" },
        tags: ["food rescue", "food insecurity", "community", "network"],
        image: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&q=80",
        rating: 4.9
    },
    {
        id: "61",
        name: "Port Laken Habitat for Humanity",
        category: "Service Stars",
        shortDescription: "Building affordable homes and stronger communities.",
        fullDescription: "Port Laken Habitat for Humanity partners with families and volunteers to build and repair homes for low-income residents. Through sweat equity and community fundraising, we've helped over 150 families achieve stable, affordable homeownership. Volunteer build days are open to everyone.",
        address: "2800 W 18th St, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.0968, lng: -123.4650 },
        phone: "(206) 555-4224",
        website: "https://plhabitat.org",
        email: "volunteer@plhabitat.org",
        socialLinks: { facebook: "fb.com/plhabitat" },
        tags: ["housing", "volunteer", "affordable homes", "community"],
        image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
        rating: 4.9
    },
    {
        id: "62",
        name: "Laken Literacy Project",
        category: "Service Stars",
        shortDescription: "Free adult literacy and ESL tutoring for Port Laken residents.",
        fullDescription: "The Laken Literacy Project provides free one-on-one tutoring and small group classes for adults seeking to improve reading, writing, and English language skills. Our volunteer tutors work with learners at all levels, from basic literacy to GED preparation and professional communication.",
        address: "318 S Lincoln St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1148, lng: -123.4370 },
        phone: "(206) 555-5252",
        website: "https://lakenliteracy.org",
        email: "learn@lakenliteracy.org",
        tags: ["literacy", "ESL", "education", "tutoring", "adult learning"],
        image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80",
        rating: 4.8
    },
    {
        id: "63",
        name: "Port Laken Clean Streets Initiative",
        category: "Service Stars",
        shortDescription: "Community-led neighborhood cleanup and beautification program.",
        fullDescription: "The Clean Streets Initiative organizes monthly neighborhood cleanups, graffiti removal, and beautification projects across Port Laken. Powered entirely by volunteers, the program has removed over 40 tons of litter and planted more than 500 trees since its founding in 2018. Join a cleanup event or adopt a block in your neighborhood.",
        address: "City Hall, 223 E 4th St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.117, lng: -123.4288 },
        phone: "(206) 555-7720",
        website: "https://plcleanstreets.org",
        email: "join@plcleanstreets.org",
        socialLinks: { instagram: "@plcleanstreets" },
        tags: ["cleanup", "volunteer", "environment", "beautification"],
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
        rating: 4.7
    },
    {
        id: "64",
        name: "Harbor Hope Homeless Outreach",
        category: "Service Stars",
        shortDescription: "Street outreach, shelter referrals, and wraparound services for unhoused residents.",
        fullDescription: "Harbor Hope provides compassionate street outreach to Port Laken's unhoused population, connecting individuals with emergency shelter, mental health services, substance use treatment, and long-term housing programs. Our outreach workers are on the streets seven days a week, meeting people where they are.",
        address: "410 W 1st St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1190, lng: -123.4430 },
        phone: "(206) 555-4673",
        website: "https://harborhope.org",
        email: "outreach@harborhope.org",
        socialLinks: { facebook: "fb.com/harborhope" },
        tags: ["homeless", "outreach", "shelter", "social services"],
        image: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800&q=80",
        rating: 4.9
    },

    // Grocery Stores
    {
        id: "65",
        name: "Kroger Port Laken",
        category: "Food",
        shortDescription: "Full-service grocery store with pharmacy and fuel center.",
        fullDescription: "Kroger Port Laken offers a wide selection of groceries, fresh produce, deli, bakery, pharmacy services, and a fuel center. The store features Kroger's digital coupons and loyalty rewards program. Open daily.",
        address: "1800 E Lauridsen Blvd, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1068, lng: -123.4135 },
        phone: "(206) 555-5600",
        website: "https://www.kroger.com",
        email: "portlaken@kroger.com",
        tags: ["grocery", "supermarket", "pharmacy", "food"],
        image: "https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&q=80",
        rating: 4.2
    },
    {
        id: "66",
        name: "Walmart Supercenter Port Laken",
        category: "Food",
        shortDescription: "Supercenter with groceries, electronics, clothing, and more.",
        fullDescription: "Port Laken's Walmart Supercenter carries a full grocery department alongside electronics, clothing, home goods, auto care, and a pharmacy. With everyday low prices and extended hours, it's a one-stop shop for the whole family.",
        address: "3200 W 18th St, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.0962, lng: -123.4710 },
        phone: "(206) 555-9200",
        website: "https://www.walmart.com",
        email: "portlaken@walmart.com",
        tags: ["grocery", "supercenter", "retail", "food", "pharmacy"],
        image: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&q=80",
        rating: 3.9
    },
    {
        id: "67",
        name: "Costco Wholesale Port Laken",
        category: "Food",
        shortDescription: "Membership warehouse club with bulk groceries and more.",
        fullDescription: "Costco Port Laken offers bulk groceries, fresh produce, meats, bakery items, electronics, furniture, and a gas station — all at warehouse prices. Membership required. The food court is a local favorite.",
        address: "4100 Old Olympic Hwy, Port Angeles, WA 98363",
        mapCoordinates: { lat: 48.0940, lng: -123.4780 },
        phone: "(206) 555-8800",
        website: "https://www.costco.com",
        email: "portlaken@costco.com",
        tags: ["grocery", "bulk", "warehouse", "membership", "food"],
        image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80",
        rating: 4.5
    },
    {
        id: "68",
        name: "Laken Market",
        category: "Food",
        shortDescription: "Port Laken's own neighborhood grocery, locally owned since 1987.",
        fullDescription: "Laken Market is Port Laken's beloved homegrown grocery store, family-owned and operated since 1987. Known for its locally sourced produce, fresh-cut meats, house-made deli items, and a curated selection of Pacific Northwest wines and craft beers. The store partners directly with regional farms and is a cornerstone of the community.",
        address: "540 E Front St, Port Angeles, WA 98362",
        mapCoordinates: { lat: 48.1186, lng: -123.4270 },
        phone: "(206) 555-1987",
        website: "https://lakenmarket.com",
        email: "hello@lakenmarket.com",
        socialLinks: { facebook: "fb.com/lakenmarket", instagram: "@lakenmarket" },
        tags: ["grocery", "local", "neighborhood", "fresh", "Port Laken"],
        image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
        rating: 4.8
    }
];